### ISSUE TITLE
Fabric 1.20.1 Server: Could not execute entrypoint stage 'main' due to errors

### ISSUE THREAD

**Issue by Spirit1998HD** [Miki-Tellurium/TurtleChargingStation#4]
Hey, when try to start the mod on a server it fails to load the mod with the following exception:

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'turtlechargingstation' at 'com.mikitellurium.turtlechargingstation.TurtleChargingStationMod'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.5.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.16.5-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_3929$class_3930
	at com.mikitellurium.turtlechargingstation.gui.ModScreens.<clinit>(ModScreens.java:16) ~[turtlechargingstation-1.5.2-1.20-fabric.jar:?]
	at com.mikitellurium.turtlechargingstation.TurtleChargingStationMod.init(TurtleChargingStationMod.java:32) ~[turtlechargingstation-1.5.2-1.20-fabric.jar:?]
	at com.mikitellurium.turtlechargingstation.TurtleChargingStationMod.onInitialize(TurtleChargingStationMod.java:24) ~[turtlechargingstation-1.5.2-1.20-fabric.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.5.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_3929$class_3930
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.5.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at com.mikitellurium.turtlechargingstation.gui.ModScreens.<clinit>(ModScreens.java:16) ~[turtlechargingstation-1.5.2-1.20-fabric.jar:?]
	at com.mikitellurium.turtlechargingstation.TurtleChargingStationMod.init(TurtleChargingStationMod.java:32) ~[turtlechargingstation-1.5.2-1.20-fabric.jar:?]
	at com.mikitellurium.turtlechargingstation.TurtleChargingStationMod.onInitialize(TurtleChargingStationMod.java:24) ~[turtlechargingstation-1.5.2-1.20-fabric.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.5.jar:?]
	... 7 more
```

The server runs fabric on mc version 1.20.1 with the fabric loader 0.16.5. Tellurium is on the newest version for fabric 1.20.1.
The client with the same mods and versions looks fine.

**Comment by Miki-Tellurium** [comment]
Some client only Classes where loaded on server during mod initialization. I made a new version for 1.20.1 that fixes this: https://modrinth.com/mod/turtle-charging-station/version/1.5.3-1.20.1-fabric

**Comment by w00tyd00d** [comment]
I'm still getting a similar crash in version 1.5.3 for Minecraft 1.20.1. I've made sure that I'm using the latest version of the TelluriumForge library (1.3.2) as well as isolated the mods to only Fabric API, CC: Tweaked, Turtle Charging Station, and the TelluriumForge library and the crash still persists.

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'turtlechargingstation' at 'com.mikitellurium.turtlechargingstation.TurtleChargingStationMod'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at knot//net.minecraft.class_310.<init>(class_310.java:458)
	at knot//net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_2591 com.mikitellurium.telluriumforge.registry.RegistryHelper.registerBlockEntity(java.lang.String, net.minecraft.class_2591)'
	at knot//com.mikitellurium.turtlechargingstation.registry.ModBlockEntities.<clinit>(ModBlockEntities.java:15)
	at knot//com.mikitellurium.turtlechargingstation.TurtleChargingStationMod.init(TurtleChargingStationMod.java:26)
	at knot//com.mikitellurium.turtlechargingstation.TurtleChargingStationMod.onInitialize(TurtleChargingStationMod.java:20)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 9 more
```

**Comment by Miki-Tellurium** [comment]
Try downgrading to TelluriumForge 1.2.2
